export const projectsData: Project[] = [
  {
    id: 7,
    title: "My Portfolio v1",
    des: "First version of this same portfolio website",
    img: "/images/myportfoliov1.jpg",
    iconLists: [
      "/icons/nextjs.svg",
      "/icons/typescript.svg",
      "/icons/framer-motion.svg",
      "/icons/html.svg",
      "/icons/css.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/nodejs.svg",
      "/icons/tailwindcss.svg",
      "/icons/github.svg"
    ],
    liveLink: "https://portfoliov1.deeja.dev/",
    category: [
      "NextJS",
      "TypeScript",
      "TailwindCSS",
      "HTML",
      "CSS",
      "Cloudflare",
      "Docker",
      "NodeJS",
      "Github",
    ],
    codeLink: "https://github.com/deejaneen/myportfoliov2",
    projectWeight: "Light",
  },
  {
    id: 8,
    title: "My Portfolio v2",
    des: "Redesigned portfolio website built to include interactivity, faster time to paint, improved SEO and accessibility -- built with more intention.",
    img: "/images/myportfoliov2.jpg",
    iconLists: [
      "/icons/nextjs.svg",
      "/icons/typescript.svg",
      "/icons/framer-motion.svg",
      "/icons/html.svg",
      "/icons/css.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/tailwindcss.svg",
      "/icons/nodejs.svg",
      "/icons/sass.svg",
      "/icons/github.svg"
    ],
    liveLink: "https://deeja.dev/",
    category: [
      "NextJS",
      "TypeScript",
      "HTML",
      "CSS",
      "Cloudflare",
      "TailwindCSS",
      "Docker",
      "NodeJS",
      "Sass",
      "Github",
    ],
    codeLink: "https://github.com/deejaneen/myportfoliov1",
    projectWeight: "Heavy",
  },
  {
    id: 2,
    title: "Horizon Bank",
    des: "Horizon is a modern banking platform for everyone",
    img: "/images/bankingnextjs.jpg",
    iconLists: [
      "/icons/nextjs.svg",
      "/icons/typescript.svg",
      "/icons/appwrite.svg",
      "/icons/plaid.svg",
      "/icons/dwolla.svg",
      "/icons/reacthookform.svg",
      "/icons/zod.svg",
      "/icons/tailwindcss.svg",
      "/icons/chartjs.svg",
      "/icons/shadcn-ui.svg",
      "/icons/html.svg",
      "/icons/css.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/nodejs.svg",
      "/icons/github.svg"
    ],
    category: [
      "NextJS",
      "TypeScript",
      "Appwrite",
      "Plaid",
      "Dwolla",
      "React Hook Form",
      "Zod",
      "TailwindCSS",
      "ChartJS",
      "ShadCN-UI",
      "HTML",
      "CSS",
      "Cloudflare",
      "Docker",
      "NodeJS",
      "Github",
    ],
    liveLink: "https://bankingnextjsapp.deeja.dev",
    codeLink: "https://github.com/deejaneen/banking_nextjs",
    projectWeight: "Heavy",
  },
  {
    id: 3,
    title: "Reservation App",
    des: "A reservation system for the facilities of COA-CAR",
    img: "/images/gadrs.JPG",
    iconLists: [
      "/icons/laravel.svg",
      "/icons/css.svg",
      "/icons/javascript.svg",
      "/icons/html.svg",
      "/icons/php.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/mariadb.svg",
      "/icons/github.svg"
    ],
    category: [
      "Laravel",
      "CSS",
      "JavaScript",
      "HTML",
      "PHP",
      "Cloudflare",
      "Docker",
      "MariaDB",
      "MySQL",
      "Github",
    ],
    liveLink: "https://gadrs.deeja.dev",
    codeLink: "https://github.com/deejaneen/GADRS",
    projectWeight: "Heavy",
  },
  {
    id: 1,
    title: "SaaS App",
    des: "Dark SaaS Landing Page",
    img: "/images/darksaaslandingpage.JPG",
    iconLists: [
      "/icons/nextjs.svg",
      "/icons/framer-motion.svg",
      "/icons/html.svg",
      "/icons/css.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/nodejs.svg",
      "/icons/typescript.svg",
      "/icons/tailwindcss.svg",
      "/icons/github.svg"
    ],
    category: [
      "NextJS",
      "Framer-Motion",
      "HTML",
      "CSS",
      "TailWindCSS",
      "Cloudflare",
      "Docker",
      "NodeJS",
      "Typescript",
      "Github",
    ],
    liveLink: "https://darksaasapp.deeja.dev",
    codeLink: "https://github.com/deejaneen/darksaaslandingpage",
    projectWeight: "Light",
  },
 
  {
    id: 4,
    title: "Hoobank Landing Page",
    des: "Dark and modern landing page for Hoobank",
    img: "/images/hoobank.JPG",
    iconLists: [
      "/icons/react.svg",
      "/icons/tailwindcss.svg",
      "/icons/vite.svg",
      "/icons/typescript.svg",
      "/icons/html.svg",
      "/icons/css.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/nodejs.svg",
      "/icons/github.svg"
    ],
    category: [
      "React",
      "TailwindCSS",
      "Vite",
      "TypeScript",
      "HTML",
      "CSS",
      "Cloudflare",
      "Docker",
      "NodeJS",
      "Github",
    ],
    liveLink: "https://hoobankapp.deeja.dev",
    codeLink: "https://github.com/deejaneen/modern_bank_app",
    projectWeight: "Light",
  },
  {
    id: 5,
    title: "Gericht Restaurant Landing",
    des: "Dark and modern landing page for Gericht Restaurant",
    img: "/images/gerichtrestaurant.JPG",
    iconLists: [
      "/icons/react.svg",
      "/icons/css.svg",
      "/icons/html.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/nodejs.svg",
      "/icons/javascript.svg",
      "/icons/github.svg"
    ],
    category: [
      "React",
      "CSS",
      "HTML",
      "Cloudflare",
      "Docker",
      "NodeJS",
      "JavaScript",
      "Github",
    ],
    liveLink: "https://gerichtapp.deeja.dev",
    codeLink: "https://github.com/deejaneen/restaurant-app-react",
    projectWeight: "Light",
  },
  {
    id: 6,
    title: "GPT3 Landing Page",
    des: "Modern landing page centered around GPT3",
    img: "/images/gpt3.JPG",
    iconLists: [
      "/icons/react.svg",
      "/icons/css.svg",
      "/icons/html.svg",
      "/icons/cloudflare.svg",
      "/icons/docker.svg",
      "/icons/nodejs.svg",
      "/icons/javascript.svg",
      "/icons/github.svg"
    ],
    liveLink: "https://gpt3app.deeja.dev",
    category: [
      "React",
      "CSS",
      "HTML",
      "Cloudflare",
      "Docker",
      "NodeJS",
      "JavaScript",
      "Github",
    ],
    codeLink: "https://github.com/deejaneen/gpt3react",
    projectWeight: "Light",
  },
 
];
